# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  #baseurl: "isp-site-template" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: miterion/isp-theme
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      # this is the standard top menu when it is not overwritten by a site
      menu: [{name: TU Darmstadt, url: "https://www.tu-darmstadt.de"}, {name: Fachbereich Informatik, url: "https://www.informatik.tu-darmstadt.de"},
      {name: ISP, url: "https://www.isp.informatik.tu-darmstadt.de"}]
      # the breadcrumbs to use, the current site will be added at the end automatically
      breadcrumbs: [{name: TU Darmstadt, url: "https://www.tu-darmstadt.de"}, {name: Informatik, url: "https://www.informatik.tu-darmstadt.de"}]
      # the title for the left sidenav
      sidenav: {mainname: Fachbereich Informatik, mainurl: 'https://www.informatik.tu-darmstadt.de'}
      # this is the standard footer, usually the contact is a webpage
      footer: [{name: Impressum, url: 'https://www.informatik.tu-darmstadt.de/index.php?id=1894'}, {name: Kontakt, url: "mailto:contact@informatik.tu-darmstadt.de"}]
